//
// Generated file, do not edit! Created by nedtool 4.6 from veins/modules/application/platooning/messages/BikesMessage.msg.
//

#ifndef _BIKESMESSAGE_M_H_
#define _BIKESMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>veins/modules/application/platooning/messages/BikesMessage.msg:1</tt> by nedtool.
 * <pre>
 * packet BikesMessage
 * {
 *     //type of vehicle generating the message
 *     int vehicleType;
 *     //id of the originator
 *     int vehicleId;
 *     //platoon id
 *     int platoonId;
 *     //message type
 *     int messageType;
 *     //platoon speed
 *     double platoonSpeed;
 *     //platoon lane
 *     int platoonLane;
 *     //id of vehicle in front of the joiner (G)
 *     int frontVehicleId;
 *     //id of the follower vehicle (F)
 *     int followerVehicleId;
 *     //platoon formation
 *     int platoonFormation[];
 * }
 * </pre>
 */
class BikesMessage : public ::cPacket
{
  protected:
    int vehicleType_var;
    int vehicleId_var;
    int platoonId_var;
    int messageType_var;
    double platoonSpeed_var;
    int platoonLane_var;
    int frontVehicleId_var;
    int followerVehicleId_var;
    int *platoonFormation_var; // array ptr
    unsigned int platoonFormation_arraysize;

  private:
    void copy(const BikesMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BikesMessage&);

  public:
    BikesMessage(const char *name=NULL, int kind=0);
    BikesMessage(const BikesMessage& other);
    virtual ~BikesMessage();
    BikesMessage& operator=(const BikesMessage& other);
    virtual BikesMessage *dup() const {return new BikesMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getVehicleType() const;
    virtual void setVehicleType(int vehicleType);
    virtual int getVehicleId() const;
    virtual void setVehicleId(int vehicleId);
    virtual int getPlatoonId() const;
    virtual void setPlatoonId(int platoonId);
    virtual int getMessageType() const;
    virtual void setMessageType(int messageType);
    virtual double getPlatoonSpeed() const;
    virtual void setPlatoonSpeed(double platoonSpeed);
    virtual int getPlatoonLane() const;
    virtual void setPlatoonLane(int platoonLane);
    virtual int getFrontVehicleId() const;
    virtual void setFrontVehicleId(int frontVehicleId);
    virtual int getFollowerVehicleId() const;
    virtual void setFollowerVehicleId(int followerVehicleId);
    virtual void setPlatoonFormationArraySize(unsigned int size);
    virtual unsigned int getPlatoonFormationArraySize() const;
    virtual int getPlatoonFormation(unsigned int k) const;
    virtual void setPlatoonFormation(unsigned int k, int platoonFormation);
};

inline void doPacking(cCommBuffer *b, BikesMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BikesMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BIKESMESSAGE_M_H_

