//
// Generated file, do not edit! Created by opp_msgc 4.4 from veins/modules/application/platooning/messages/PlatooningBeacon.msg.
//

#ifndef _PLATOONINGBEACON_M_H_
#define _PLATOONINGBEACON_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>veins/modules/application/platooning/messages/PlatooningBeacon.msg</tt> by opp_msgc.
 * <pre>
 * packet PlatooningBeacon {
 * 	
 * 	int vehicleId = 0;
 * 	
 * 	int relayerId = 0;
 * 	double acceleration = 0;
 * 	double speed = 0;
 * 	double positionX = 0;
 * 	double positionY = 0;
 * 	double time = 0;
 * 	int sequenceNumber = 0;
 * }
 * </pre>
 */
class PlatooningBeacon : public ::cPacket
{
  protected:
    int vehicleId_var;
    int relayerId_var;
    double acceleration_var;
    double speed_var;
    double positionX_var;
    double positionY_var;
    double time_var;
    int sequenceNumber_var;

  private:
    void copy(const PlatooningBeacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlatooningBeacon&);

  public:
    PlatooningBeacon(const char *name=NULL, int kind=0);
    PlatooningBeacon(const PlatooningBeacon& other);
    virtual ~PlatooningBeacon();
    PlatooningBeacon& operator=(const PlatooningBeacon& other);
    virtual PlatooningBeacon *dup() const {return new PlatooningBeacon(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getVehicleId() const;
    virtual void setVehicleId(int vehicleId);
    virtual int getRelayerId() const;
    virtual void setRelayerId(int relayerId);
    virtual double getAcceleration() const;
    virtual void setAcceleration(double acceleration);
    virtual double getSpeed() const;
    virtual void setSpeed(double speed);
    virtual double getPositionX() const;
    virtual void setPositionX(double positionX);
    virtual double getPositionY() const;
    virtual void setPositionY(double positionY);
    virtual double getTime() const;
    virtual void setTime(double time);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doPacking(cCommBuffer *b, PlatooningBeacon& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PlatooningBeacon& obj) {obj.parsimUnpack(b);}


#endif // _PLATOONINGBEACON_M_H_
