//
// Generated file, do not edit! Created by nedtool 4.6 from veins/modules/application/platooning/messages/UnicastMessage.msg.
//

#ifndef _UNICASTMESSAGE_M_H_
#define _UNICASTMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>veins/modules/application/platooning/messages/UnicastMessage.msg:18</tt> by nedtool.
 * <pre>
 * enum UnicastMessageType
 * {
 * 
 *     DATA = 0;
 *     ACK = 1;
 * }
 * </pre>
 */
enum UnicastMessageType {
    DATA = 0,
    ACK = 1
};

/**
 * Class generated from <tt>veins/modules/application/platooning/messages/UnicastMessage.msg:26</tt> by nedtool.
 * <pre>
 * //
 * // Unicast message sent by the unicast protocol
 * //
 * packet UnicastMessage
 * {
 *     //destination MAC address
 *     int destination;
 *     //source MAC address
 *     int source;
 *     //sequence number
 *     int sequenceNumber;
 *     //message type, data or ack
 *     int type @enum(UnicastMessageType);
 *     //priority for the message (will be then mapped onto an AC)
 *     //0 = AC_BK
 *     //1 = AC_BE
 *     //2 = AC_VI
 *     //3 = AC_VO
 *     int priority = 0;
 *     //receive power in dBm
 *     double recvPower_dBm;
 *     //channel (0 CCH, 1 SCH)
 *     int channel;
 * }
 * </pre>
 */
class UnicastMessage : public ::cPacket
{
  protected:
    int destination_var;
    int source_var;
    int sequenceNumber_var;
    int type_var;
    int priority_var;
    double recvPower_dBm_var;
    int channel_var;

  private:
    void copy(const UnicastMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UnicastMessage&);

  public:
    UnicastMessage(const char *name=NULL, int kind=0);
    UnicastMessage(const UnicastMessage& other);
    virtual ~UnicastMessage();
    UnicastMessage& operator=(const UnicastMessage& other);
    virtual UnicastMessage *dup() const {return new UnicastMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual int getType() const;
    virtual void setType(int type);
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual double getRecvPower_dBm() const;
    virtual void setRecvPower_dBm(double recvPower_dBm);
    virtual int getChannel() const;
    virtual void setChannel(int channel);
};

inline void doPacking(cCommBuffer *b, UnicastMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, UnicastMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _UNICASTMESSAGE_M_H_

